kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: imagedir
        path: /imagedir
    commands:
      - docker build -t paperplanecc/hospital-api:latest .
      - docker image save paperplanecc/hospital-api:latest > /imagedir/hospital-api.tar

  - name: prepare-docker
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - docker stop hospital-api || true
        - docker rm hospital-api || true
        - docker image rm paperplanecc/hospital-api:latest || true
        - docker image load < /root/images-export/hospital-api.tar

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/hospital
        - docker compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: imagedir
    host:
      path: /root/images-export

trigger:
  branch:
    - master
