kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: npmcache
        path: /usr/local/share/.cache/yarn
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/hospital-be
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    volumes:
      - name: ssh
        path: /sshpath
    settings:
      host: a-c.fun
      username: ubuntu
      key_path: /sshpath/id_rsa
      port: 22
      command_timeout: 5m
      script:
        - cd /data/docker/default
        - sudo docker pull paperplanecc/hospital-be:latest
        - sudo docker-compose up -d

volumes:
  - name: npmcache
    host:
      path: /data/npmcache
  - name: ssh
    host:
      path: /home/ubuntu/drone-deploy-ssh

trigger:
  branch:
  - master
