kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/hospital-be
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: a-c.fun
      username: ubuntu
      password:
        from_secret: SSH_PASSWORD
      port: 22
      command_timeout: 5m
      script:
        - cd /data/docker/default
        - sudo docker pull paperplanecc/hospital-be:latest
        - sudo docker-compose up -d

trigger:
  branch:
    - master
