kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: plugins/docker
    settings:
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repo: $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io
      tags: latest
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_IMAGE_NAME:
        from_secret: DOCKER_IMAGE_NAME

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - $SERVER_HOST
      username: $SSH_USERNAME
      password: $SSH_PASSWORD
      port: 22
      command_timeout: 5m
      script:
        - sudo su
        - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
        - docker run -it -d --name $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
      environment:
        SERVER_HOST:
          from_secret: SERVER_HOST
        SSH_USERNAME:
          from_secret: SSH_USERNAME
        SSH_PASSWORD:
          from_secret: SSH_PASSWORD
        DOCKER_USERNAME:
          from_secret: DOCKER_USERNAME
        DOCKER_IMAGE_NAME:
          from_secret: DOCKER_IMAGE_NAME

trigger:
  branch:
    - master
