kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: plugins/docker
    settings:
      username: paperplanecc
      password: dckr_pat_U77IJVpjjTQQd1E8Rl_-OCQbT2Q
      repo: paperplanecc/hospital

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      username: ubuntu
      password: ${SSH_PASSWORD}
      port: 22
      command_timeout: 5m
      script:
        - sudo su
        - docker pull paperplanecc/hospital
        - docker run -it -d --name hospital paperplanecc/hospital:latest

trigger:
  branch:
    - master
