kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: npmcache
        path: /usr/local/share/.cache/yarn
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/hospital-be
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    volumes:
      - name: ssh
        path: /sshpath
      - name: homepath
        path: /homepath
    commands:
      - cp -f /home/node/app/docker-compose.yml /homepath/hospital-be-docker-compose.yml
    settings:
      host: a-c.fun
      username: ubuntu
      key_path: /sshpath/id_rsa
      port: 22
      command_timeout: 5m
      script:
        - cd /home/ubuntu
        - sudo docker pull paperplanecc/hospital-be:latest
        - sudo docker-compose up -d -f hospital-be-docker-compose.yml

volumes:
  - name: npmcache
    host:
      path: /home/ubuntu/npmcache
  - name: ssh
    host:
      path: /home/ubuntu/drone-deploy-ssh
  - name: homepath
    host:
      path: /homepath

trigger:
  branch:
    - master
