kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - docker build --progress plain --compress -t paperplanecc/hospital-api:ci .

  - name: prepare-docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop hospital-api || true
      - docker rm hospital-api || true
      - docker image rm paperplanecc/hospital-api:latest || true
      - docker tag paperplanecc/hospital-api:ci paperplanecc/hospital-api:latest || true
      - docker image rm paperplanecc/hospital-api:ci || true

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/hospital
        - docker compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
