kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/hospital-be
      tags: latest
      mirror: https://mirror.ccs.tencentyun.com
      registry: docker.io
  
  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: [ "a-c.fun" ]
      user: ubuntu
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      source: ./docker-compose.yml
      target: /home/ubuntu/hospital-be-docker-compose.yml
      script:
        - docker pull paperplanecc/hospital-be:latest
        - cd /home/ubuntu
        - export COMPOSE_PROJECT_NAME=ubuntu
        - docker-compose -f hospital-be-docker-compose.yml up -d

trigger:
  branch:
    - master
