version: '3'

networks:
  be:
    external: true

services:
  hospital-be:
    image: paperplanecc/hospital-be:latest
    container_name: hospital-be
    networks:
      - be
    environment:
      - NODE_ENV=production
