version: '3'

networks:
  default-app:
    name: default-app
    external: true
  default-db-mongo:
    name: default-db-mongo
    external: true

services:
  hospital-be:
    image: paperplanecc/hospital-be:latest
    container_name: hospital-be
    restart: always
    networks:
      - default-app
      - default-db-mongo
    environment:
      - NODE_ENV=production
