version: '3'

networks:
  ubuntu_be:
    external: true

services:
  hospital-be:
    image: paperplanecc/hospital-be:latest
    container_name: hospital-be
    restart: always
    networks:
      - ubuntu_be
    environment:
      - NODE_ENV=production
